### ISSUE TITLE
Using ft!help with a command (Caesarcrypt, for example) just brings up the main page of help

### ISSUE THREAD

**Issue by emre7000** [Fossium-Team/fossdiscord-old#26]
read title

**Comment by emre7000** [comment]
![grafik](https://user-images.githubusercontent.com/80070059/126043544-1e4140dc-80fd-44a3-a76a-0adee8b4b29a.png)

**Comment by SKBotNL** [comment]
hmm, lemme fix this. i think i removed it when making the new help command

**Comment by SKBotNL** [comment]
Fixed in 77e4904c6855de03b8191b7300a811f482b4898e

**Comment by SKBotNL** [comment]
NVM, I actually didn't fix anything. You are using a category instead of an actual command

**Comment by emre7000** [comment]
wut
